### ISSUE TITLE
Use or Example

### ISSUE THREAD

**Issue by ashraful1980** [UnleashMe69/HashesDB#1]
Sir,
How to use HashesDB.exe; please give me a valid example. Also how to connect MySQL4.1/5.....

Thanks & Regards,
Ashraful

**Comment by UnleashMe69** [comment]
So, you first need to import your hashes.
Let's say you have a file containing your hashes in the following format 
`hash:plaintext` such as sql5.hashes included in the _example_ folder.

After building HashesDB or using the compiled executable included, you then use the following command to:

1. Create a database named _SQL5_db_
2. Import your hashes from _sql5.hashes_ to _SQL5_db_ and you specify the hash type: **SQL5**

`HashesDB.exe -i  sql5.hashes SQL5 SQL5_db`

At this point, your new database named _SQL5_db_ is created (the db is a folder, containing many many files depending on the database size. You should not edit those files under any circumstances) and all hashes from _sql5.hashes_ should be successfully imported.

The output should look like something like the following:

`database created with success.

counting lines in pot file

1000 lines to import.

importing lines from  pot file to database...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
0 seconds to import 1000 lines.
`
Now, for cracking some hashes, you can download _CMIYC.sql5_ file containing randomly selected hashes from _sql5.hashes_.
To test the cracking process let's use the following command:

`HashesDB.exe -c CMIYC.sql5 SQL5_db`

1. At this point, HashesDB reads all hashes from _CMIYC.sql5_ and will look into the database _sql5.hashes_ created previously if it contains the hashes we want to crack.
2. HashesDB then prints the cracked hashes in a new file named _cracked_hashes.txt_

The output should look something like the following:
`counting number of hashes to crack
cracking hashes now...


0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
0 seconds to crack 230 hashes.```

**Comment by UnleashMe69** [comment]
So, you first need to import your hashes.
Let's say you have a file containing your hashes in the following format 
`hash:plaintext` such as sql5.hashes included in the _example_ folder.

After building HashesDB or using the compiled executable included, you then use the following command to:

1. Create a database named _SQL5_db_
2. Import your hashes from _sql5.hashes_ to _SQL5_db_ and you specify the hash type: **SQL5**

`HashesDB.exe -i  sql5.hashes SQL5 SQL5_db`

At this point, your new database named _SQL5_db_ is created (the db is a folder, containing many many files depending on the database size. You should not edit those files under any circumstances) and all hashes from _sql5.hashes_ should be successfully imported.

The output should look like something like the following:

`database created with success.`
`counting lines in pot file`
`1000 lines to import.`
`importing lines from  pot file to database...`

`0%   10   20   30   40   50   60   70   80   90   100%`
`|----|----|----|----|----|----|----|----|----|----|`
`***************************************************`
`0 seconds to import 1000 lines.`

Now, for cracking some hashes, you can download _CMIYC.sql5_ file containing randomly selected hashes from _sql5.hashes_.
To test the cracking process let's use the following command:

`HashesDB.exe -c CMIYC.sql5 SQL5_db`

1. At this point, HashesDB reads all hashes from _CMIYC.sql5_ and will look into the database _sql5.hashes_ created previously if it contains the hashes we want to crack.
2. HashesDB then prints the cracked hashes in a new file named _cracked_hashes.txt_

The output should look something like the following:

`counting number of hashes to crack`
`cracking hashes now...`
`0%   10   20   30   40   50   60   70   80   90   100%`
`|----|----|----|----|----|----|----|----|----|----|`
`***************************************************`
`0 seconds to crack 230 hashes.`

**Comment by ashraful1980** [comment]
Dear Sir,
Thanks for your guideline; please let me know that to possible cracking as bellow hash. It is a sample hash I need to crack as same hash. If it is possible I will contribute lot of amount. So please let me know about it...

  Password		                        : Encrypted Master Key                                                   
01.  =Sj8vrvEcJ8nLyGd		        : YmM6K91ZVYN3NwFpiLk3hqtcgkmx1FxXu7pUu8R/kklq56OCQMk1b9/TUoQ5AQAMtHSK   
02.  3+4fr_SgbA+8%m+E		: YmM6xPoE2D/fG1UMiWWVyjFP800lQFJa/EwswNsPM1z0XW/IVam9AhzJnBNPAQC2Eg5H  
03.  ty%Q63H**N&3QQts		: YmM6257z8E0bS2yVJ8834n6NfisK5tmt1USbwMm5Wk6vOk610XuTOBDIcI1KAQDmmRBw   
04.  zfbmk45An4RC%dM_		: YmM6ynbPDFVybmWLb/VBO0tkqN/SXu/Cwh7ETIxyjHvoSj+IcSOyGTnaJ2QqAQAVi5oX   
05.  K4zQjKPKe_&D+#Rb		: YmM6j/DFLTAmrIuUn9xkRE1NrsveGfi/s/tLPhmf21r/gzm1ugPkBPHXnb/qAQC1yhPI    
06.  +4@Zx9%YDwHKXYKk		: YmM6neUpBR2Ai100xnnEMCCiM+a1Fh3i6FBwEnAJ1h5MJMgJeStHhvNoy3u/AAAlR44F

**Comment by UnleashMe69** [comment]
> Dear Sir,
> Thanks for your guideline; please let me know that to possible cracking as bellow hash. It is a sample hash I need to crack as same hash. If it is possible I will contribute lot of amount. So please let me know about it...

I am afraid I do not do cracking requests!
HashesDB is not a magical tool, it is an embedded database so **YOU** can store **YOUR** cracked hashes, that way, when you stumble upon a hash, you can ask HashesDB if **YOU** already cracked the hash previously.
HashesDB cannot and does not crack hashes from thin air, it is just a database to contain **YOUR** cracked hashes!

**Comment by ashraful1980** [comment]
Dear Sir,
Thanks for your valuable suggestions to me.....
